# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('reminder_for', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Other', 'Other')], default='Birthday', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateField(auto_now=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('monthly_email_sent', models.BooleanField(default=False)),
                ('weekly_email_sent', models.BooleanField(default=False)),
                ('daily_email_sent', models.BooleanField(default=False)),
                ('important_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_calendar.ImportantDate')),
            ],
        ),
    ]
